from typing import cast, Optional

from web3 import Web3
from web3.middleware import geth_poa_middleware, construct_simple_cache_middleware
from web3.types import RPCEndpoint

# Eliminate unnecessary eth_chainId (and other) queries.
# https://ethereum.stackexchange.com/questions/131768/how-to-reduce-the-number-of-eth-chainid-calls-when-using-web3-python
SIMPLE_CACHE_RPC_CHAIN_ID = cast(
    set[RPCEndpoint],
    (
        "web3_clientVersion",
        "net_version",
        "eth_chainId",
    ),
)

# Added this caching originally to streamline the RPCs generated by this server when we were using a paid RPC provider.
# No reason to remove it though, since there's no reason to be fetching chain id anyway.
cache_chain_id_middleware = construct_simple_cache_middleware(
    rpc_whitelist=SIMPLE_CACHE_RPC_CHAIN_ID
)

# Every supported chain needs a mapping from chain id to rpc endpoint.
CHAIN_ID_TO_RPC = {
    8453: 'https://mainnet.base.org',
    84531: 'https://goerli.base.org',
}


def make_web3(node_uri: str) -> Web3:
    """Creates a web3 from a node uri, accounting for websocket vs http."""
    if node_uri.startswith('http'):
        return Web3(Web3.HTTPProvider(node_uri))
    elif node_uri.startswith('ws'):
        return Web3(Web3.WebsocketProvider(node_uri))
    else:
        raise Exception(f'node_uri not valid: {node_uri}')


def make_complete_web3(node_uri: str) -> Web3:
    """Given a node uri, creates a web3 properly configured."""
    w3 = make_web3(node_uri)
    # Inject the POA middleware
    w3.middleware_onion.inject(geth_poa_middleware, layer=0)
    # Always cache chain_id
    w3.middleware_onion.add(cache_chain_id_middleware, name="Cache chain_id")
    return w3


def make_web3_for_chain_id(chain_id: int, rpc_endpoint_override: Optional[str] = None) -> Web3:
    """Given a chain id, creates a web3 properly configured."""
    return make_complete_web3(rpc_endpoint_override or CHAIN_ID_TO_RPC[chain_id])
